// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    access_token: '<%= delivery_token %>',
    management_token: '<%= management_token %>',
    space_id: '<%= space_id %>',
    content_types: {}
  };

}).call(this);
